# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Opsgeniex.Api.TeamRole do
  @moduledoc """
  API calls for all endpoints tagged `TeamRole`.
  """

  alias Opsgeniex.Connection
  import Opsgeniex.RequestBuilder

  @doc """
  Create Team Role
  Creates a new team role

  ### Parameters

  - `connection` (Opsgeniex.Connection): Connection to server
  - `identifier` (String.t): Identifier of the team
  - `body` (CreateTeamRolePayload): Request payload of created team role
  - `opts` (keyword): Optional parameters
    - `:teamIdentifierType` (String.t): Type of the identifier. Possible values are 'id' and 'name'. Default value is 'id'

  ### Returns

  - `{:ok, Opsgeniex.Model.SuccessResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec create_team_role(Tesla.Env.client, String.t, Opsgeniex.Model.CreateTeamRolePayload.t, keyword()) :: {:ok, Opsgeniex.Model.ErrorResponse.t} | {:ok, Opsgeniex.Model.SuccessResponse.t} | {:error, Tesla.Env.t}
  def create_team_role(connection, identifier, body, opts \\ []) do
    optional_params = %{
      :teamIdentifierType => :query
    }

    request =
      %{}
      |> method(:post)
      |> url("/v2/teams/#{identifier}/roles")
      |> add_param(:body, :body, body)
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {201, Opsgeniex.Model.SuccessResponse},
      {400, Opsgeniex.Model.ErrorResponse},
      {401, Opsgeniex.Model.ErrorResponse},
      {402, Opsgeniex.Model.ErrorResponse},
      {403, Opsgeniex.Model.ErrorResponse},
      {404, Opsgeniex.Model.ErrorResponse},
      {422, Opsgeniex.Model.ErrorResponse},
      {429, Opsgeniex.Model.ErrorResponse},
      {:default, Opsgeniex.Model.ErrorResponse}
    ])
  end

  @doc """
  Delete Team Role
  Deletes a team role using team role 'id' or 'name'

  ### Parameters

  - `connection` (Opsgeniex.Connection): Connection to server
  - `identifier` (String.t): Identifier of the team
  - `team_role_identifier` (String.t): Identifier of team role which could be team role 'id' or 'name'
  - `opts` (keyword): Optional parameters
    - `:teamIdentifierType` (String.t): Type of the identifier. Possible values are 'id' and 'name'. Default value is 'id'
    - `:identifierType` (String.t): Type of the identifier that is provided as an in-line parameter. Possible values are 'id' or 'name'

  ### Returns

  - `{:ok, Opsgeniex.Model.SuccessResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec delete_team_role(Tesla.Env.client, String.t, String.t, keyword()) :: {:ok, Opsgeniex.Model.ErrorResponse.t} | {:ok, Opsgeniex.Model.SuccessResponse.t} | {:error, Tesla.Env.t}
  def delete_team_role(connection, identifier, team_role_identifier, opts \\ []) do
    optional_params = %{
      :teamIdentifierType => :query,
      :identifierType => :query
    }

    request =
      %{}
      |> method(:delete)
      |> url("/v2/teams/#{identifier}/roles/#{team_role_identifier}")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, Opsgeniex.Model.SuccessResponse},
      {400, Opsgeniex.Model.ErrorResponse},
      {401, Opsgeniex.Model.ErrorResponse},
      {402, Opsgeniex.Model.ErrorResponse},
      {403, Opsgeniex.Model.ErrorResponse},
      {404, Opsgeniex.Model.ErrorResponse},
      {429, Opsgeniex.Model.ErrorResponse},
      {:default, Opsgeniex.Model.ErrorResponse}
    ])
  end

  @doc """
  Get Team Role
  Returns team role with given 'id' or 'name'

  ### Parameters

  - `connection` (Opsgeniex.Connection): Connection to server
  - `identifier` (String.t): Identifier of the team
  - `team_role_identifier` (String.t): Identifier of team role which could be team role 'id' or 'name'
  - `opts` (keyword): Optional parameters
    - `:teamIdentifierType` (String.t): Type of the identifier. Possible values are 'id' and 'name'. Default value is 'id'
    - `:identifierType` (String.t): Type of the identifier that is provided as an in-line parameter. Possible values are 'id' or 'name'

  ### Returns

  - `{:ok, Opsgeniex.Model.GetTeamRoleResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_team_role(Tesla.Env.client, String.t, String.t, keyword()) :: {:ok, Opsgeniex.Model.ErrorResponse.t} | {:ok, Opsgeniex.Model.GetTeamRoleResponse.t} | {:error, Tesla.Env.t}
  def get_team_role(connection, identifier, team_role_identifier, opts \\ []) do
    optional_params = %{
      :teamIdentifierType => :query,
      :identifierType => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/v2/teams/#{identifier}/roles/#{team_role_identifier}")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, Opsgeniex.Model.GetTeamRoleResponse},
      {400, Opsgeniex.Model.ErrorResponse},
      {401, Opsgeniex.Model.ErrorResponse},
      {402, Opsgeniex.Model.ErrorResponse},
      {403, Opsgeniex.Model.ErrorResponse},
      {404, Opsgeniex.Model.ErrorResponse},
      {429, Opsgeniex.Model.ErrorResponse},
      {:default, Opsgeniex.Model.ErrorResponse}
    ])
  end

  @doc """
  List Team Roles
  Returns list of team roles

  ### Parameters

  - `connection` (Opsgeniex.Connection): Connection to server
  - `identifier` (String.t): Identifier of the team
  - `opts` (keyword): Optional parameters
    - `:teamIdentifierType` (String.t): Type of the identifier. Possible values are 'id' and 'name'. Default value is 'id'

  ### Returns

  - `{:ok, Opsgeniex.Model.ListTeamRoleResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec list_team_roles(Tesla.Env.client, String.t, keyword()) :: {:ok, Opsgeniex.Model.ListTeamRoleResponse.t} | {:ok, Opsgeniex.Model.ErrorResponse.t} | {:error, Tesla.Env.t}
  def list_team_roles(connection, identifier, opts \\ []) do
    optional_params = %{
      :teamIdentifierType => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/v2/teams/#{identifier}/roles")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, Opsgeniex.Model.ListTeamRoleResponse},
      {400, Opsgeniex.Model.ErrorResponse},
      {401, Opsgeniex.Model.ErrorResponse},
      {402, Opsgeniex.Model.ErrorResponse},
      {403, Opsgeniex.Model.ErrorResponse},
      {422, Opsgeniex.Model.ErrorResponse},
      {429, Opsgeniex.Model.ErrorResponse},
      {:default, Opsgeniex.Model.ErrorResponse}
    ])
  end

  @doc """
  Update Team Role (Partial)
  Updates the team role using team role 'id' or 'name'

  ### Parameters

  - `connection` (Opsgeniex.Connection): Connection to server
  - `identifier` (String.t): Identifier of the team
  - `team_role_identifier` (String.t): Identifier of team role which could be team role 'id' or 'name'
  - `opts` (keyword): Optional parameters
    - `:teamIdentifierType` (String.t): Type of the identifier. Possible values are 'id' and 'name'. Default value is 'id'
    - `:identifierType` (String.t): Type of the identifier that is provided as an in-line parameter. Possible values are 'id' or 'name'
    - `:body` (UpdateTeamRolePayload): Request payload of update team role

  ### Returns

  - `{:ok, Opsgeniex.Model.SuccessResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec update_team_role(Tesla.Env.client, String.t, String.t, keyword()) :: {:ok, Opsgeniex.Model.ErrorResponse.t} | {:ok, Opsgeniex.Model.SuccessResponse.t} | {:error, Tesla.Env.t}
  def update_team_role(connection, identifier, team_role_identifier, opts \\ []) do
    optional_params = %{
      :teamIdentifierType => :query,
      :identifierType => :query,
      :body => :body
    }

    request =
      %{}
      |> method(:patch)
      |> url("/v2/teams/#{identifier}/roles/#{team_role_identifier}")
      |> add_optional_params(optional_params, opts)
      |> ensure_body()
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, Opsgeniex.Model.SuccessResponse},
      {400, Opsgeniex.Model.ErrorResponse},
      {401, Opsgeniex.Model.ErrorResponse},
      {402, Opsgeniex.Model.ErrorResponse},
      {403, Opsgeniex.Model.ErrorResponse},
      {404, Opsgeniex.Model.ErrorResponse},
      {422, Opsgeniex.Model.ErrorResponse},
      {429, Opsgeniex.Model.ErrorResponse},
      {:default, Opsgeniex.Model.ErrorResponse}
    ])
  end
end
