# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Opsgeniex.Model.AccountInfo do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :name,
    :userCount,
    :plan
  ]

  @type t :: %__MODULE__{
    :name => String.t | nil,
    :userCount => integer() | nil,
    :plan => Opsgeniex.Model.AccountPlan.t | nil
  }

  alias Opsgeniex.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:plan, :struct, Opsgeniex.Model.AccountPlan)
  end
end

