# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Opsgeniex.Model.AccountPlan do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :maxUserCount,
    :name,
    :isYearly
  ]

  @type t :: %__MODULE__{
    :maxUserCount => integer() | nil,
    :name => String.t | nil,
    :isYearly => boolean() | nil
  }

  def decode(value) do
    value
  end
end

