# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Opsgeniex.Model.ActionCategorized do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :_parent,
    :ignore,
    :create,
    :close,
    :acknowledge,
    :addNote
  ]

  @type t :: %__MODULE__{
    :_parent => Opsgeniex.Model.IntegrationMeta.t | nil,
    :ignore => [Opsgeniex.Model.IgnoreIntegrationAction.t] | nil,
    :create => [Opsgeniex.Model.CreateIntegrationAction.t] | nil,
    :close => [Opsgeniex.Model.CloseIntegrationAction.t] | nil,
    :acknowledge => [Opsgeniex.Model.AckIntegrationAction.t] | nil,
    :addNote => [Opsgeniex.Model.AddNoteIntegrationAction.t] | nil
  }

  alias Opsgeniex.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:_parent, :struct, Opsgeniex.Model.IntegrationMeta)
     |> Deserializer.deserialize(:ignore, :list, Opsgeniex.Model.IgnoreIntegrationAction)
     |> Deserializer.deserialize(:create, :list, Opsgeniex.Model.CreateIntegrationAction)
     |> Deserializer.deserialize(:close, :list, Opsgeniex.Model.CloseIntegrationAction)
     |> Deserializer.deserialize(:acknowledge, :list, Opsgeniex.Model.AckIntegrationAction)
     |> Deserializer.deserialize(:addNote, :list, Opsgeniex.Model.AddNoteIntegrationAction)
  end
end

