# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Opsgeniex.Model.ActionMapping do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :action,
    :extraField,
    :extraFieldForMappedAction,
    :mappedAction
  ]

  @type t :: %__MODULE__{
    :action => String.t,
    :extraField => String.t | nil,
    :extraFieldForMappedAction => String.t | nil,
    :mappedAction => String.t | nil
  }

  def decode(value) do
    value
  end
end

