# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Opsgeniex.Model.AddTeamToAlertPayload do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :user,
    :note,
    :source,
    :team
  ]

  @type t :: %__MODULE__{
    :user => String.t | nil,
    :note => String.t | nil,
    :source => String.t | nil,
    :team => Opsgeniex.Model.TeamRecipient.t
  }

  alias Opsgeniex.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:team, :struct, Opsgeniex.Model.TeamRecipient)
  end
end

