# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Opsgeniex.Model.AddNoteIntegrationAction do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :name,
    :order,
    :filter,
    :type,
    :user,
    :note,
    :alias
  ]

  @type t :: %__MODULE__{
    :name => String.t | nil,
    :order => integer() | nil,
    :filter => Opsgeniex.Model.IntegrationActionFilter.t | nil,
    :type => String.t,
    :user => String.t | nil,
    :note => String.t | nil,
    :alias => String.t | nil
  }

  alias Opsgeniex.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:filter, :struct, Opsgeniex.Model.IntegrationActionFilter)
  end
end

