# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Opsgeniex.Model.AlertLog do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :log,
    :type,
    :owner,
    :createdAt,
    :offset
  ]

  @type t :: %__MODULE__{
    :log => String.t | nil,
    :type => String.t | nil,
    :owner => String.t | nil,
    :createdAt => DateTime.t | nil,
    :offset => String.t | nil
  }

  alias Opsgeniex.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:createdAt, :datetime, nil)
  end
end

