# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Opsgeniex.Model.AlertRecipient do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :user,
    :state,
    :method,
    :createdAt,
    :updatedAt
  ]

  @type t :: %__MODULE__{
    :user => Opsgeniex.Model.AlertUserMeta.t | nil,
    :state => String.t | nil,
    :method => String.t | nil,
    :createdAt => DateTime.t | nil,
    :updatedAt => DateTime.t | nil
  }

  alias Opsgeniex.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:user, :struct, Opsgeniex.Model.AlertUserMeta)
     |> Deserializer.deserialize(:createdAt, :datetime, nil)
     |> Deserializer.deserialize(:updatedAt, :datetime, nil)
  end
end

