# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Opsgeniex.Model.AlertAttachmentMeta do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :name,
    :id
  ]

  @type t :: %__MODULE__{
    :name => String.t | nil,
    :id => String.t | nil
  }

  def decode(value) do
    value
  end
end

