# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Opsgeniex.Model.AlertReport do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :ackTime,
    :closeTime,
    :acknowledgedBy,
    :closedBy
  ]

  @type t :: %__MODULE__{
    :ackTime => integer() | nil,
    :closeTime => integer() | nil,
    :acknowledgedBy => String.t | nil,
    :closedBy => String.t | nil
  }

  def decode(value) do
    value
  end
end

