# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Opsgeniex.Model.AutoRestartAction do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :duration,
    :maxRepeatCount
  ]

  @type t :: %__MODULE__{
    :duration => Opsgeniex.Model.Duration.t,
    :maxRepeatCount => integer()
  }

  alias Opsgeniex.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:duration, :struct, Opsgeniex.Model.Duration)
  end
end

