# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Opsgeniex.Model.BaseResponseWithExpandable do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :requestId,
    :took,
    :expandable
  ]

  @type t :: %__MODULE__{
    :requestId => String.t,
    :took => float(),
    :expandable => [String.t] | nil
  }

  def decode(value) do
    value
  end
end

