# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Opsgeniex.Model.ChangeTeamRoutingRuleOrderPayload do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :order
  ]

  @type t :: %__MODULE__{
    :order => integer() | nil
  }

  def decode(value) do
    value
  end
end

