# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Opsgeniex.Model.Contact do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :method,
    :to,
    :status
  ]

  @type t :: %__MODULE__{
    :id => String.t | nil,
    :method => String.t | nil,
    :to => String.t | nil,
    :status => Opsgeniex.Model.ContactStatus.t | nil
  }

  alias Opsgeniex.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:status, :struct, Opsgeniex.Model.ContactStatus)
  end
end

