# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Opsgeniex.Model.CreateNotificationRuleStepPayload do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :contact,
    :sendAfter,
    :enabled
  ]

  @type t :: %__MODULE__{
    :contact => Opsgeniex.Model.ContactMeta.t,
    :sendAfter => Opsgeniex.Model.Duration.t | nil,
    :enabled => boolean()
  }

  alias Opsgeniex.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:contact, :struct, Opsgeniex.Model.ContactMeta)
     |> Deserializer.deserialize(:sendAfter, :struct, Opsgeniex.Model.Duration)
  end
end

