# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Opsgeniex.Model.CreateSavedSearchPayload do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :name,
    :description,
    :query,
    :owner,
    :teams
  ]

  @type t :: %__MODULE__{
    :name => String.t,
    :description => String.t | nil,
    :query => String.t,
    :owner => Opsgeniex.Model.UserRecipient.t,
    :teams => [Opsgeniex.Model.TeamRecipient.t] | nil
  }

  alias Opsgeniex.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:owner, :struct, Opsgeniex.Model.UserRecipient)
     |> Deserializer.deserialize(:teams, :list, Opsgeniex.Model.TeamRecipient)
  end
end

