# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Opsgeniex.Model.CreateHeartbeatPayload do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :name,
    :description,
    :interval,
    :intervalUnit,
    :enabled
  ]

  @type t :: %__MODULE__{
    :name => String.t,
    :description => String.t | nil,
    :interval => integer(),
    :intervalUnit => String.t,
    :enabled => boolean()
  }

  def decode(value) do
    value
  end
end

