# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Opsgeniex.Model.CreateIncidentPayload do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :message,
    :description,
    :responders,
    :tags,
    :details,
    :priority,
    :note,
    :serviceId,
    :statusPageEntry,
    :notifyStakeholders
  ]

  @type t :: %__MODULE__{
    :message => String.t,
    :description => String.t | nil,
    :responders => [Opsgeniex.Model.Recipient.t] | nil,
    :tags => [String.t] | nil,
    :details => %{optional(String.t) => String.t} | nil,
    :priority => String.t | nil,
    :note => String.t | nil,
    :serviceId => String.t,
    :statusPageEntry => %{optional(String.t) => Opsgeniex.Model.StatusPageEntry.t} | nil,
    :notifyStakeholders => boolean() | nil
  }

  alias Opsgeniex.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:responders, :list, Opsgeniex.Model.Recipient)
     |> Deserializer.deserialize(:statusPageEntry, :map, Opsgeniex.Model.StatusPageEntry)
  end
end

