# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Opsgeniex.Model.CreateUserPayload do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :username,
    :fullName,
    :role,
    :skypeUsername,
    :timeZone,
    :locale,
    :userAddress,
    :tags,
    :details,
    :invitationDisabled
  ]

  @type t :: %__MODULE__{
    :username => String.t,
    :fullName => String.t,
    :role => Opsgeniex.Model.UserRole.t,
    :skypeUsername => String.t | nil,
    :timeZone => String.t | nil,
    :locale => String.t | nil,
    :userAddress => Opsgeniex.Model.UserAddress.t | nil,
    :tags => [String.t] | nil,
    :details => %{optional(String.t) => [String.t]} | nil,
    :invitationDisabled => boolean() | nil
  }

  alias Opsgeniex.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:role, :struct, Opsgeniex.Model.UserRole)
     |> Deserializer.deserialize(:userAddress, :struct, Opsgeniex.Model.UserAddress)
  end
end

