# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Opsgeniex.Model.CreateIntegrationAction do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :name,
    :order,
    :filter,
    :type,
    :user,
    :note,
    :alias,
    :source,
    :message,
    :description,
    :entity,
    :priority,
    :appendAttachments,
    :alertActions,
    :ignoreAlertActionsFromPayload,
    :recipients,
    :ignoreRecipientsFromPayload,
    :ignoreTeamsFromPayload,
    :tags,
    :ignoreTagsFromPayload,
    :extraProperties,
    :ignoreExtraPropertiesFromPayload
  ]

  @type t :: %__MODULE__{
    :name => String.t | nil,
    :order => integer() | nil,
    :filter => Opsgeniex.Model.IntegrationActionFilter.t | nil,
    :type => String.t,
    :user => String.t | nil,
    :note => String.t | nil,
    :alias => String.t | nil,
    :source => String.t | nil,
    :message => String.t | nil,
    :description => String.t | nil,
    :entity => String.t | nil,
    :priority => String.t | nil,
    :appendAttachments => boolean() | nil,
    :alertActions => [String.t] | nil,
    :ignoreAlertActionsFromPayload => boolean() | nil,
    :recipients => [Opsgeniex.Model.Recipient.t] | nil,
    :ignoreRecipientsFromPayload => boolean() | nil,
    :ignoreTeamsFromPayload => boolean() | nil,
    :tags => [String.t] | nil,
    :ignoreTagsFromPayload => boolean() | nil,
    :extraProperties => %{optional(String.t) => String.t} | nil,
    :ignoreExtraPropertiesFromPayload => boolean() | nil
  }

  alias Opsgeniex.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:filter, :struct, Opsgeniex.Model.IntegrationActionFilter)
     |> Deserializer.deserialize(:recipients, :list, Opsgeniex.Model.Recipient)
  end
end

