# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Opsgeniex.Model.CreateAlertPayload do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :user,
    :note,
    :source,
    :message,
    :alias,
    :description,
    :teams,
    :visibleTo,
    :actions,
    :tags,
    :details,
    :entity,
    :priority
  ]

  @type t :: %__MODULE__{
    :user => String.t | nil,
    :note => String.t | nil,
    :source => String.t | nil,
    :message => String.t,
    :alias => String.t | nil,
    :description => String.t | nil,
    :teams => [Opsgeniex.Model.TeamRecipient.t] | nil,
    :visibleTo => [Opsgeniex.Model.Recipient.t] | nil,
    :actions => [String.t] | nil,
    :tags => [String.t] | nil,
    :details => %{optional(String.t) => String.t} | nil,
    :entity => String.t | nil,
    :priority => String.t | nil
  }

  alias Opsgeniex.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:teams, :list, Opsgeniex.Model.TeamRecipient)
     |> Deserializer.deserialize(:visibleTo, :list, Opsgeniex.Model.Recipient)
  end
end

