# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Opsgeniex.Model.CreateScheduleOverridePayload do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :alias,
    :user,
    :startDate,
    :endDate,
    :rotations
  ]

  @type t :: %__MODULE__{
    :alias => String.t,
    :user => Opsgeniex.Model.Recipient.t,
    :startDate => DateTime.t,
    :endDate => DateTime.t,
    :rotations => [Opsgeniex.Model.ScheduleOverrideRotation.t] | nil
  }

  alias Opsgeniex.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:user, :struct, Opsgeniex.Model.Recipient)
     |> Deserializer.deserialize(:startDate, :datetime, nil)
     |> Deserializer.deserialize(:endDate, :datetime, nil)
     |> Deserializer.deserialize(:rotations, :list, Opsgeniex.Model.ScheduleOverrideRotation)
  end
end

