# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Opsgeniex.Model.CreateHeartbeatPayload do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :name,
    :description,
    :interval,
    :intervalUnit,
    :enabled,
    :ownerTeam,
    :alertMessage,
    :alertTags,
    :alertPriority
  ]

  @type t :: %__MODULE__{
    :name => String.t,
    :description => String.t | nil,
    :interval => integer(),
    :intervalUnit => String.t,
    :enabled => boolean(),
    :ownerTeam => Opsgeniex.Model.CreateHeartbeatPayloadAllOfOwnerTeam.t | nil,
    :alertMessage => String.t | nil,
    :alertTags => [String.t] | nil,
    :alertPriority => String.t | nil
  }

  alias Opsgeniex.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:ownerTeam, :struct, Opsgeniex.Model.CreateHeartbeatPayloadAllOfOwnerTeam)
  end
end

