# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Opsgeniex.Model.CreateForwardingRulePayload do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :fromUser,
    :toUser,
    :startDate,
    :endDate,
    :alias
  ]

  @type t :: %__MODULE__{
    :fromUser => Opsgeniex.Model.UserMeta.t,
    :toUser => Opsgeniex.Model.UserMeta.t,
    :startDate => DateTime.t,
    :endDate => DateTime.t,
    :alias => String.t | nil
  }

  alias Opsgeniex.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:fromUser, :struct, Opsgeniex.Model.UserMeta)
     |> Deserializer.deserialize(:toUser, :struct, Opsgeniex.Model.UserMeta)
     |> Deserializer.deserialize(:startDate, :datetime, nil)
     |> Deserializer.deserialize(:endDate, :datetime, nil)
  end
end

