# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Opsgeniex.Model.DelayAction do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :delayOption,
    :untilHour,
    :untilMinute,
    :duration
  ]

  @type t :: %__MODULE__{
    :delayOption => String.t,
    :untilHour => integer() | nil,
    :untilMinute => integer() | nil,
    :duration => Opsgeniex.Model.Duration.t | nil
  }

  alias Opsgeniex.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:duration, :struct, Opsgeniex.Model.Duration)
  end
end

