# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Opsgeniex.Model.DeprecatedChangeAlertPolicyOrderPayload do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :targetIndex
  ]

  @type t :: %__MODULE__{
    :targetIndex => integer()
  }

  def decode(value) do
    value
  end
end

