# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Opsgeniex.Model.DeprecatedModifyAlertPolicy do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :name,
    :policyDescription,
    :filter,
    :timeRestrictions,
    :enabled,
    :type,
    :ignoreOriginalAlertActions,
    :ignoreOriginalDetails,
    :ignoreOriginalRecipients,
    :ignoreOriginalTags,
    :ignoreOriginalTeams,
    :continue,
    :alias,
    :description,
    :entity,
    :message,
    :source,
    :actions,
    :recipients,
    :tags,
    :details,
    :priority
  ]

  @type t :: %__MODULE__{
    :id => String.t | nil,
    :name => String.t | nil,
    :policyDescription => String.t | nil,
    :filter => Opsgeniex.Model.Filter.t | nil,
    :timeRestrictions => Opsgeniex.Model.TimeRestrictionInterval.t | nil,
    :enabled => boolean() | nil,
    :type => String.t,
    :ignoreOriginalAlertActions => boolean() | nil,
    :ignoreOriginalDetails => boolean() | nil,
    :ignoreOriginalRecipients => boolean() | nil,
    :ignoreOriginalTags => boolean() | nil,
    :ignoreOriginalTeams => boolean() | nil,
    :continue => boolean() | nil,
    :alias => String.t | nil,
    :description => String.t | nil,
    :entity => String.t | nil,
    :message => String.t | nil,
    :source => String.t | nil,
    :actions => [String.t] | nil,
    :recipients => [Opsgeniex.Model.Recipient.t] | nil,
    :tags => [String.t] | nil,
    :details => %{optional(String.t) => String.t} | nil,
    :priority => String.t | nil
  }

  alias Opsgeniex.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:filter, :struct, Opsgeniex.Model.Filter)
     |> Deserializer.deserialize(:timeRestrictions, :struct, Opsgeniex.Model.TimeRestrictionInterval)
     |> Deserializer.deserialize(:recipients, :list, Opsgeniex.Model.Recipient)
  end
end

