# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Opsgeniex.Model.Duration do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :timeAmount,
    :timeUnit
  ]

  @type t :: %__MODULE__{
    :timeAmount => integer(),
    :timeUnit => String.t | nil
  }

  def decode(value) do
    value
  end
end

