# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Opsgeniex.Model.EscalationRepeat do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :waitInterval,
    :count,
    :resetRecipientStates,
    :closeAlertAfterAll
  ]

  @type t :: %__MODULE__{
    :waitInterval => integer() | nil,
    :count => integer() | nil,
    :resetRecipientStates => boolean() | nil,
    :closeAlertAfterAll => boolean() | nil
  }

  def decode(value) do
    value
  end
end

