# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Opsgeniex.Model.EscalationRule do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :condition,
    :notifyType,
    :delay,
    :recipient
  ]

  @type t :: %__MODULE__{
    :condition => String.t,
    :notifyType => String.t,
    :delay => Opsgeniex.Model.Duration.t,
    :recipient => Opsgeniex.Model.Recipient.t
  }

  alias Opsgeniex.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:delay, :struct, Opsgeniex.Model.Duration)
     |> Deserializer.deserialize(:recipient, :struct, Opsgeniex.Model.Recipient)
  end
end

