# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Opsgeniex.Model.Heartbeat do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :name,
    :description,
    :interval,
    :enabled,
    :intervalUnit,
    :expired,
    :lastPingTime
  ]

  @type t :: %__MODULE__{
    :name => String.t | nil,
    :description => String.t | nil,
    :interval => integer() | nil,
    :enabled => boolean() | nil,
    :intervalUnit => String.t | nil,
    :expired => boolean() | nil,
    :lastPingTime => DateTime.t | nil
  }

  alias Opsgeniex.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:lastPingTime, :datetime, nil)
  end
end

