# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Opsgeniex.Model.HeartbeatMeta do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :name,
    :enabled,
    :expired
  ]

  @type t :: %__MODULE__{
    :name => String.t | nil,
    :enabled => boolean() | nil,
    :expired => boolean() | nil
  }

  def decode(value) do
    value
  end
end

