# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Opsgeniex.Model.IgnoreIntegrationAction do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :name,
    :order,
    :filter,
    :type
  ]

  @type t :: %__MODULE__{
    :name => String.t,
    :order => integer() | nil,
    :filter => Opsgeniex.Model.IntegrationActionFilter.t,
    :type => String.t
  }

  alias Opsgeniex.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:filter, :struct, Opsgeniex.Model.IntegrationActionFilter)
  end
end

