# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Opsgeniex.Model.ListHeartbeatResponseAllOfData do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :heartbeats
  ]

  @type t :: %__MODULE__{
    :heartbeats => [Opsgeniex.Model.Heartbeat.t] | nil
  }

  alias Opsgeniex.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:heartbeats, :list, Opsgeniex.Model.Heartbeat)
  end
end

