# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Opsgeniex.Model.MaintenanceTime do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :type,
    :startDate,
    :endDate
  ]

  @type t :: %__MODULE__{
    :type => String.t,
    :startDate => DateTime.t | nil,
    :endDate => DateTime.t | nil
  }

  alias Opsgeniex.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:startDate, :datetime, nil)
     |> Deserializer.deserialize(:endDate, :datetime, nil)
  end
end

