# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Opsgeniex.Model.MaintenanceRule do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :state,
    :entity
  ]

  @type t :: %__MODULE__{
    :state => String.t | nil,
    :entity => Opsgeniex.Model.MaintenanceEntity.t
  }

  alias Opsgeniex.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:entity, :struct, Opsgeniex.Model.MaintenanceEntity)
  end
end

