# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Opsgeniex.Model.NotificationRuleMeta do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :name,
    :actionType,
    :order,
    :enabled
  ]

  @type t :: %__MODULE__{
    :id => String.t | nil,
    :name => String.t | nil,
    :actionType => Opsgeniex.Model.NotificationActionType.t | nil,
    :order => integer() | nil,
    :enabled => boolean() | nil
  }

  alias Opsgeniex.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:actionType, :struct, Opsgeniex.Model.NotificationActionType)
  end
end

