# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Opsgeniex.Model.NotificationRuleStep do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :_parent,
    :id,
    :sendAfter,
    :contact,
    :enabled
  ]

  @type t :: %__MODULE__{
    :_parent => Opsgeniex.Model.NotificationRuleStepParent.t | nil,
    :id => String.t | nil,
    :sendAfter => Opsgeniex.Model.Duration.t | nil,
    :contact => Opsgeniex.Model.ContactMeta.t | nil,
    :enabled => boolean() | nil
  }

  alias Opsgeniex.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:_parent, :struct, Opsgeniex.Model.NotificationRuleStepParent)
     |> Deserializer.deserialize(:sendAfter, :struct, Opsgeniex.Model.Duration)
     |> Deserializer.deserialize(:contact, :struct, Opsgeniex.Model.ContactMeta)
  end
end

