# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Opsgeniex.Model.NotificationPolicy do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :name,
    :policyDescription,
    :teamId,
    :filter,
    :timeRestrictions,
    :enabled,
    :type,
    :autoRestartAction,
    :autoCloseAction,
    :deduplicationAction,
    :delayAction,
    :suppress
  ]

  @type t :: %__MODULE__{
    :id => String.t | nil,
    :name => String.t | nil,
    :policyDescription => String.t | nil,
    :teamId => String.t | nil,
    :filter => Opsgeniex.Model.Filter.t | nil,
    :timeRestrictions => Opsgeniex.Model.TimeRestrictionInterval.t | nil,
    :enabled => boolean() | nil,
    :type => String.t,
    :autoRestartAction => Opsgeniex.Model.AutoRestartAction.t | nil,
    :autoCloseAction => Opsgeniex.Model.AutoCloseAction.t | nil,
    :deduplicationAction => Opsgeniex.Model.DeduplicationAction.t | nil,
    :delayAction => Opsgeniex.Model.DelayAction.t | nil,
    :suppress => boolean() | nil
  }

  alias Opsgeniex.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:filter, :struct, Opsgeniex.Model.Filter)
     |> Deserializer.deserialize(:timeRestrictions, :struct, Opsgeniex.Model.TimeRestrictionInterval)
     |> Deserializer.deserialize(:autoRestartAction, :struct, Opsgeniex.Model.AutoRestartAction)
     |> Deserializer.deserialize(:autoCloseAction, :struct, Opsgeniex.Model.AutoCloseAction)
     |> Deserializer.deserialize(:deduplicationAction, :struct, Opsgeniex.Model.DeduplicationAction)
     |> Deserializer.deserialize(:delayAction, :struct, Opsgeniex.Model.DelayAction)
  end
end

