# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Opsgeniex.Model.NotificationRepeat do
  @moduledoc """
  The amount of time in minutes that notification steps will be repeatedly apply
  """

  @derive Jason.Encoder
  defstruct [
    :loopAfter,
    :enabled
  ]

  @type t :: %__MODULE__{
    :loopAfter => integer() | nil,
    :enabled => boolean() | nil
  }

  def decode(value) do
    value
  end
end

