# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Opsgeniex.Model.OnCall do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :_parent,
    :onCallParticipants,
    :onCallRecipients
  ]

  @type t :: %__MODULE__{
    :_parent => Opsgeniex.Model.ScheduleMeta.t | nil,
    :onCallParticipants => [Opsgeniex.Model.Participant.t] | nil,
    :onCallRecipients => [String.t] | nil
  }

  alias Opsgeniex.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:_parent, :struct, Opsgeniex.Model.ScheduleMeta)
     |> Deserializer.deserialize(:onCallParticipants, :list, Opsgeniex.Model.Participant)
  end
end

