# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Opsgeniex.Model.PageDetails do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :prev,
    :next,
    :first,
    :last
  ]

  @type t :: %__MODULE__{
    :prev => String.t | nil,
    :next => String.t | nil,
    :first => String.t | nil,
    :last => String.t | nil
  }

  def decode(value) do
    value
  end
end

