# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Opsgeniex.Model.SavedSearch do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :name,
    :createdAt,
    :updatedAt,
    :owner,
    :teams,
    :description,
    :query
  ]

  @type t :: %__MODULE__{
    :id => String.t | nil,
    :name => String.t | nil,
    :createdAt => DateTime.t | nil,
    :updatedAt => DateTime.t | nil,
    :owner => Opsgeniex.Model.SavedSearchEntity.t | nil,
    :teams => [Opsgeniex.Model.SavedSearchEntity.t] | nil,
    :description => String.t | nil,
    :query => String.t | nil
  }

  alias Opsgeniex.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:createdAt, :datetime, nil)
     |> Deserializer.deserialize(:updatedAt, :datetime, nil)
     |> Deserializer.deserialize(:owner, :struct, Opsgeniex.Model.SavedSearchEntity)
     |> Deserializer.deserialize(:teams, :list, Opsgeniex.Model.SavedSearchEntity)
  end
end

