# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Opsgeniex.Model.ScheduleOverride do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :_parent,
    :alias,
    :user,
    :startDate,
    :endDate,
    :rotations
  ]

  @type t :: %__MODULE__{
    :_parent => Opsgeniex.Model.ScheduleMeta.t | nil,
    :alias => String.t | nil,
    :user => Opsgeniex.Model.Recipient.t | nil,
    :startDate => DateTime.t | nil,
    :endDate => DateTime.t | nil,
    :rotations => [Opsgeniex.Model.ScheduleOverrideRotation.t] | nil
  }

  alias Opsgeniex.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:_parent, :struct, Opsgeniex.Model.ScheduleMeta)
     |> Deserializer.deserialize(:user, :struct, Opsgeniex.Model.Recipient)
     |> Deserializer.deserialize(:startDate, :datetime, nil)
     |> Deserializer.deserialize(:endDate, :datetime, nil)
     |> Deserializer.deserialize(:rotations, :list, Opsgeniex.Model.ScheduleOverrideRotation)
  end
end

