# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Opsgeniex.Model.ScheduleTimeline do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :_parent,
    :startDate,
    :endDate,
    :finalTimeline,
    :baseTimeline,
    :overrideTimeline,
    :forwardingTimeline
  ]

  @type t :: %__MODULE__{
    :_parent => Opsgeniex.Model.ScheduleMeta.t | nil,
    :startDate => DateTime.t | nil,
    :endDate => DateTime.t | nil,
    :finalTimeline => Opsgeniex.Model.Timeline.t | nil,
    :baseTimeline => Opsgeniex.Model.Timeline.t | nil,
    :overrideTimeline => Opsgeniex.Model.Timeline.t | nil,
    :forwardingTimeline => Opsgeniex.Model.Timeline.t | nil
  }

  alias Opsgeniex.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:_parent, :struct, Opsgeniex.Model.ScheduleMeta)
     |> Deserializer.deserialize(:startDate, :datetime, nil)
     |> Deserializer.deserialize(:endDate, :datetime, nil)
     |> Deserializer.deserialize(:finalTimeline, :struct, Opsgeniex.Model.Timeline)
     |> Deserializer.deserialize(:baseTimeline, :struct, Opsgeniex.Model.Timeline)
     |> Deserializer.deserialize(:overrideTimeline, :struct, Opsgeniex.Model.Timeline)
     |> Deserializer.deserialize(:forwardingTimeline, :struct, Opsgeniex.Model.Timeline)
  end
end

