# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Opsgeniex.Model.ScheduleOverrideMeta do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :alias
  ]

  @type t :: %__MODULE__{
    :alias => String.t | nil
  }

  def decode(value) do
    value
  end
end

