# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Opsgeniex.Model.ServiceAudienceTemplate do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :responder,
    :stakeholder
  ]

  @type t :: %__MODULE__{
    :responder => Opsgeniex.Model.ServiceAudienceTemplateResponder.t | nil,
    :stakeholder => Opsgeniex.Model.ServiceAudienceTemplateStakeholder.t | nil
  }

  alias Opsgeniex.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:responder, :struct, Opsgeniex.Model.ServiceAudienceTemplateResponder)
     |> Deserializer.deserialize(:stakeholder, :struct, Opsgeniex.Model.ServiceAudienceTemplateStakeholder)
  end
end

