# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Opsgeniex.Model.ServiceAudienceTemplateResponder do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :teams,
    :individuals
  ]

  @type t :: %__MODULE__{
    :teams => [String.t] | nil,
    :individuals => [String.t] | nil
  }

  def decode(value) do
    value
  end
end

