# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Opsgeniex.Model.ServiceIncidentStakeholderProperties do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :enable,
    :message,
    :description
  ]

  @type t :: %__MODULE__{
    :enable => boolean() | nil,
    :message => String.t,
    :description => String.t | nil
  }

  def decode(value) do
    value
  end
end

