# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Opsgeniex.Model.ServiceIncidentProperties do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :message,
    :tags,
    :details,
    :description,
    :priority,
    :stakeholderProperties
  ]

  @type t :: %__MODULE__{
    :message => String.t,
    :tags => [String.t] | nil,
    :details => %{optional(String.t) => String.t} | nil,
    :description => String.t | nil,
    :priority => String.t,
    :stakeholderProperties => Opsgeniex.Model.ServiceIncidentStakeholderProperties.t
  }

  alias Opsgeniex.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:stakeholderProperties, :struct, Opsgeniex.Model.ServiceIncidentStakeholderProperties)
  end
end

