# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Opsgeniex.Model.TeamLogDetails do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :owner,
    :createdDate,
    :log
  ]

  @type t :: %__MODULE__{
    :owner => String.t | nil,
    :createdDate => DateTime.t | nil,
    :log => String.t | nil
  }

  alias Opsgeniex.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:createdDate, :datetime, nil)
  end
end

