# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Opsgeniex.Model.TeamLog do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :offset,
    :logs
  ]

  @type t :: %__MODULE__{
    :offset => String.t | nil,
    :logs => [Opsgeniex.Model.TeamLogDetails.t] | nil
  }

  alias Opsgeniex.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:logs, :list, Opsgeniex.Model.TeamLogDetails)
  end
end

