# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Opsgeniex.Model.TimeRestrictionInterval do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :type
  ]

  @type t :: %__MODULE__{
    :type => String.t
  }

  def decode(value) do
    value
  end
end

