# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Opsgeniex.Model.TimelinePeriod do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :startDate,
    :endDate,
    :type,
    :fromUser,
    :recipient,
    :flattenedRecipients
  ]

  @type t :: %__MODULE__{
    :startDate => DateTime.t | nil,
    :endDate => DateTime.t | nil,
    :type => String.t | nil,
    :fromUser => String.t | nil,
    :recipient => Opsgeniex.Model.TimelineRecipient.t | nil,
    :flattenedRecipients => [Opsgeniex.Model.TimelineRecipient.t] | nil
  }

  alias Opsgeniex.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:startDate, :datetime, nil)
     |> Deserializer.deserialize(:endDate, :datetime, nil)
     |> Deserializer.deserialize(:recipient, :struct, Opsgeniex.Model.TimelineRecipient)
     |> Deserializer.deserialize(:flattenedRecipients, :list, Opsgeniex.Model.TimelineRecipient)
  end
end

