# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Opsgeniex.Model.TimeOfDayRestrictionInterval do
  @moduledoc """
  Time of day restriction interval
  """

  @derive Jason.Encoder
  defstruct [
    :type,
    :restriction
  ]

  @type t :: %__MODULE__{
    :type => String.t,
    :restriction => Opsgeniex.Model.TimeOfDayRestriction.t | nil
  }

  alias Opsgeniex.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:restriction, :struct, Opsgeniex.Model.TimeOfDayRestriction)
  end
end

