# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Opsgeniex.Model.UpdateCustomUserRolePayload do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :name,
    :extendedRole,
    :grantedRights,
    :disallowedRights
  ]

  @type t :: %__MODULE__{
    :name => String.t | nil,
    :extendedRole => String.t | nil,
    :grantedRights => [String.t] | nil,
    :disallowedRights => [String.t] | nil
  }

  def decode(value) do
    value
  end
end

