# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Opsgeniex.Model.UpdateTeamRolePayload do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :name,
    :rights
  ]

  @type t :: %__MODULE__{
    :name => String.t | nil,
    :rights => [Opsgeniex.Model.TeamRight.t] | nil
  }

  alias Opsgeniex.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:rights, :list, Opsgeniex.Model.TeamRight)
  end
end

