# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Opsgeniex.Model.UpdateNotificationRulePayload do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :name,
    :criteria,
    :notificationTime,
    :timeRestriction,
    :schedules,
    :steps,
    :repeat,
    :order,
    :enabled
  ]

  @type t :: %__MODULE__{
    :name => String.t | nil,
    :criteria => Opsgeniex.Model.Filter.t | nil,
    :notificationTime => [Opsgeniex.Model.NotifyTime.t] | nil,
    :timeRestriction => Opsgeniex.Model.TimeRestrictionInterval.t | nil,
    :schedules => [Opsgeniex.Model.ScheduleRecipient.t] | nil,
    :steps => [Opsgeniex.Model.CreateNotificationRuleStepPayload.t] | nil,
    :repeat => Opsgeniex.Model.NotificationRepeat.t | nil,
    :order => integer() | nil,
    :enabled => boolean() | nil
  }

  alias Opsgeniex.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:criteria, :struct, Opsgeniex.Model.Filter)
     |> Deserializer.deserialize(:notificationTime, :list, Opsgeniex.Model.NotifyTime)
     |> Deserializer.deserialize(:timeRestriction, :struct, Opsgeniex.Model.TimeRestrictionInterval)
     |> Deserializer.deserialize(:schedules, :list, Opsgeniex.Model.ScheduleRecipient)
     |> Deserializer.deserialize(:steps, :list, Opsgeniex.Model.CreateNotificationRuleStepPayload)
     |> Deserializer.deserialize(:repeat, :struct, Opsgeniex.Model.NotificationRepeat)
  end
end

