# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Opsgeniex.Model.UserAddress do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :country,
    :state,
    :city,
    :line,
    :zipCode
  ]

  @type t :: %__MODULE__{
    :country => String.t | nil,
    :state => String.t | nil,
    :city => String.t | nil,
    :line => String.t | nil,
    :zipCode => String.t | nil
  }

  def decode(value) do
    value
  end
end

