# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Opsgeniex.Model.User do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :username,
    :fullName,
    :role,
    :skypeUsername,
    :timeZone,
    :locale,
    :userAddress,
    :tags,
    :details,
    :blocked,
    :verified,
    :createdAt,
    :mutedUntil,
    :userContacts
  ]

  @type t :: %__MODULE__{
    :id => String.t | nil,
    :username => String.t | nil,
    :fullName => String.t | nil,
    :role => Opsgeniex.Model.UserRole.t | nil,
    :skypeUsername => String.t | nil,
    :timeZone => String.t | nil,
    :locale => String.t | nil,
    :userAddress => Opsgeniex.Model.UserAddress.t | nil,
    :tags => [String.t] | nil,
    :details => %{optional(String.t) => [String.t]} | nil,
    :blocked => boolean() | nil,
    :verified => boolean() | nil,
    :createdAt => DateTime.t | nil,
    :mutedUntil => DateTime.t | nil,
    :userContacts => [Opsgeniex.Model.UserContact.t] | nil
  }

  alias Opsgeniex.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:role, :struct, Opsgeniex.Model.UserRole)
     |> Deserializer.deserialize(:userAddress, :struct, Opsgeniex.Model.UserAddress)
     |> Deserializer.deserialize(:createdAt, :datetime, nil)
     |> Deserializer.deserialize(:mutedUntil, :datetime, nil)
     |> Deserializer.deserialize(:userContacts, :list, Opsgeniex.Model.UserContact)
  end
end

