# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Opsgeniex.Model.WeekdayTimeRestrictionInterval do
  @moduledoc """
  Weekday time restriction interval
  """

  @derive Jason.Encoder
  defstruct [
    :type,
    :restrictions
  ]

  @type t :: %__MODULE__{
    :type => String.t,
    :restrictions => [Opsgeniex.Model.WeekdayTimeRestriction.t] | nil
  }

  alias Opsgeniex.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:restrictions, :list, Opsgeniex.Model.WeekdayTimeRestriction)
  end
end

