# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Opsgeniex.Model.WeekdayTimeRestriction do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :startDay,
    :startHour,
    :startMin,
    :endDay,
    :endHour,
    :endMin
  ]

  @type t :: %__MODULE__{
    :startDay => String.t | nil,
    :startHour => integer() | nil,
    :startMin => integer() | nil,
    :endDay => String.t | nil,
    :endHour => integer() | nil,
    :endMin => integer() | nil
  }

  def decode(value) do
    value
  end
end

